# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "main-backend-tcc-1119"
    dynamodb_table = "dynamodb-tcc-1119"
    encrypt        = true
    key            = "eks1/terraform.tfstate"
    region         = "us-east-1"
  }
}
